name: Automated Tests
on: [pull_request]
jobs:
  rspec:
    name: Rspec Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rspec
